package cookies

import (
	"bufio"
	"fmt"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"
)

// GoogleDomains is the default set of domains extracted for Google Photos auth.
var GoogleDomains = []string{
	".google.com",
	".google.it",
	"accounts.google.com",
	"photos.google.com",
	"photos.fife.usercontent.google.com",
}

// NetscapeLine holds one parsed line from a Netscape cookie jar.
type NetscapeLine struct {
	Domain   string
	Flag     bool // TRUE if domain-wide
	Path     string
	Secure   bool
	Expires  int64 // Unix timestamp, 0 = session
	Name     string
	Value    string
	HTTPOnly bool
}

// ParseNetscapeJar reads a Netscape cookie file and returns parsed lines.
// Lines beginning with '#' (or #HttpOnly_) are handled correctly.
func ParseNetscapeJar(path string) ([]NetscapeLine, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open jar %s: %w", path, err)
	}
	defer f.Close()

	var lines []NetscapeLine
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		raw := sc.Text()

		// Strip #HttpOnly_ prefix before processing
		httpOnly := false
		if strings.HasPrefix(raw, "#HttpOnly_") {
			httpOnly = true
			raw = raw[len("#HttpOnly_"):]
		}

		// Skip comment lines (but not #HttpOnly_ ones after stripping)
		if strings.HasPrefix(raw, "#") || strings.TrimSpace(raw) == "" {
			continue
		}

		fields := strings.Split(raw, "\t")
		if len(fields) < 7 {
			continue
		}

		expires, _ := strconv.ParseInt(fields[4], 10, 64)
		lines = append(lines, NetscapeLine{
			Domain:   fields[0],
			Flag:     strings.ToUpper(fields[1]) == "TRUE",
			Path:     fields[2],
			Secure:   strings.ToUpper(fields[3]) == "TRUE",
			Expires:  expires,
			Name:     fields[5],
			Value:    fields[6],
			HTTPOnly: httpOnly,
		})
	}
	return lines, sc.Err()
}

// WriteNetscapeJar writes a Netscape cookie jar file from CookieRows.
func WriteNetscapeJar(path string, rows []CookieRow) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create jar %s: %w", path, err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	_, _ = fmt.Fprintln(w, "# Netscape HTTP Cookie File")
	_, _ = fmt.Fprintln(w, "# Generated by revoco")
	_, _ = fmt.Fprintln(w)

	for _, r := range rows {
		prefix := ""
		if r.HTTPOnly {
			prefix = "#HttpOnly_"
		}
		domainFlag := "FALSE"
		if strings.HasPrefix(r.Host, ".") {
			domainFlag = "TRUE"
		}
		secureFl := "FALSE"
		if r.Secure {
			secureFl = "TRUE"
		}
		var expiresUnix int64
		if !r.ExpiresAt.IsZero() {
			expiresUnix = r.ExpiresAt.Unix()
		}
		_, _ = fmt.Fprintf(w, "%s%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
			prefix, r.Host, domainFlag, r.Path, secureFl, expiresUnix, r.Name, r.Value)
	}
	return w.Flush()
}

// LoadNetscapeCookieJar reads a Netscape jar file and returns an http.CookieJar
// ready for use with http.Client.
func LoadNetscapeCookieJar(path string) (http.CookieJar, error) {
	lines, err := ParseNetscapeJar(path)
	if err != nil {
		return nil, err
	}

	jar, err := cookiejar.New(nil)
	if err != nil {
		return nil, err
	}

	// Group by scheme+host
	byHost := make(map[string][]*http.Cookie)
	for _, l := range lines {
		scheme := "http"
		if l.Secure {
			scheme = "https"
		}
		key := scheme + "://" + strings.TrimPrefix(l.Domain, ".")
		var exp time.Time
		if l.Expires > 0 {
			exp = time.Unix(l.Expires, 0)
		}
		c := &http.Cookie{
			Name:     l.Name,
			Value:    l.Value,
			Path:     l.Path,
			Domain:   l.Domain,
			Expires:  exp,
			Secure:   l.Secure,
			HttpOnly: l.HTTPOnly,
		}
		byHost[key] = append(byHost[key], c)
	}

	for rawURL, cookies := range byHost {
		u, err := url.Parse(rawURL)
		if err != nil {
			continue
		}
		jar.SetCookies(u, cookies)
	}
	return jar, nil
}
